### ISSUE TITLE
[Bug]: Can't install the nuxt-vuetify module due to splat-operator "@" being in the script

### ISSUE THREAD

**Issue by Firabe** [invictus-codes/nuxt-vuetify#7]
### Contact Details

holm.konstantin@gmail.com

### What happened?

Greetings,

I have initialized a Nuxt3 project with npx nuxi init, changed into the directory, ran an npm install and afterwards wanted to install the vuetify module via npm install --save-dev @invictus.codes/nuxt-vuetify

However, this has led to the error

+ npm install --save-dev @invictus.codes/nuxt-vuetify
+                        ~~~~~~~~~
Der Splat-Operator "@" kann nicht dazu verwendet werden, auf Variablen in einem Ausdruck zu verweisen. "@invictus" kann nur als      
Argument für einen Befehl verwendet werden. Wenn Sie auf Variablen in einem Ausdruck verweisen möchten, verwenden Sie "$invictus".   
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

It has an issue with the @ being in front of invictus.codes. This also happens on npm and pnpm. Any solutions?

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
+ npm install --save-dev @invictus.codes/nuxt-vuetify
+                        ~~~~~~~~~
Der Splat-Operator "@" kann nicht dazu verwendet werden, auf Variablen in einem Ausdruck zu verweisen. "@invictus" kann nur als      
Argument für einen Befehl verwendet werden. Wenn Sie auf Variablen in einem Ausdruck verweisen möchten, verwenden Sie "$invictus".   
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

### Additional context

![grafik](https://user-images.githubusercontent.com/9089036/234286768-02a75338-becf-4ec1-8abd-01afdd943f84.png)

**Comment by jvhellemondt** [comment]
Are you using PowerShell? The @ symbol seems to be [something](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting) on it. I'd say you get this more often?

I'm not sure if this works, you might be able to install with quotes around the package name, `npm install "@invictus.codes/nuxt-vuetify@^0.2.20"`.

Another workaround might be (and it's not fancy) to use an alias (`npm install <alias>@npm:<name>`), e.g. `npm install nuxt-vuetify@npm:@invictus.codes/nuxt-vuetify@^0.2.20`

Haven't tested both yet though.

Another option, you can manually add the package within your package.json under devDependencies. 

Last resort (based on the info/ assumptions I have), try a different terminal instead of PowerShell like cmd or git bash. 

Let me know if any of this works!

**Comment by Firabe** [comment]
> Are you using PowerShell? The @ symbol seems to be [something](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting) on it. I'd say you get this more often?
> 
> I'm not sure if this works, you might be able to install with quotes around the package name, `npm install "@invictus.codes/nuxt-vuetify@^0.2.20"`.
> 
> Another workaround might be (and it's not fancy) to use an alias (`npm install <alias>@npm:<name>`), e.g. `npm install nuxt-vuetify@npm:@invictus.codes/nuxt-vuetify@^0.2.20`
> 
> Haven't tested both yet though.
> 
> Another option, you can manually add the package within your package.json under devDependencies.
> 
> Last resort (based on the info/ assumptions I have), try a different terminal instead of PowerShell like cmd or git bash.
> 
> Let me know if any of this works!

Ah, putting the package name in quotes helped me, thank you very much!
